# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'SDCycleScrollView', :git =>'https://github.com/gsdios/SDCycleScrollView.git', :inhibit_warnings => true
  pod 'YYModel', :git => 'https://github.com/ibireme/YYModel.git', :inhibit_warnings => true
  pod 'TZImagePickerController',:git =>'https://github.com/banchichen/TZImagePickerController.git',:inhibit_warnings => true
  pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :inhibit_warnings => true
  pod 'SGQRCode', '~> 3.0.1'
  pod 'LZYVendor', :git => 'https://github.com/GItHubNanmu77/LZYVendor.git',:tag => '1.0.0', :inhibit_warnings => true
  # Pods for ShareBook

  target 'ShareBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShareBookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
