# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'AFNetworking', '~> 3.2.1',:inhibit_warnings => true
  #pod 'SDWebImage', :git =>'https://github.com/SDWebImage/SDWebImage.git', :inhibit_warnings => true
  pod 'SDCycleScrollView', :git =>'https://github.com/gsdios/SDCycleScrollView.git', :inhibit_warnings => true
  pod 'Masonry', :git => 'https://github.com/SnapKit/Masonry.git', :inhibit_warnings => true
  pod 'YYModel', :git => 'https://github.com/ibireme/YYModel.git', :inhibit_warnings => true
  pod 'TZImagePickerController',:git =>'https://github.com/banchichen/TZImagePickerController.git',:inhibit_warnings => true
  pod 'YTKNetwork', :git => 'https://github.com/yuantiku/YTKNetwork.git', :inhibit_warnings => true
  pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :inhibit_warnings => true
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git', :inhibit_warnings => true
  pod 'SGQRCode', '~> 3.0.1'
  
  
  # Pods for ShareBook

  target 'ShareBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShareBookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
